export const cards = [
  {
    imgSrc: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=300&q=80",
    imgAlt: "EchoedLightStudio Profile",
    title: "EchoedLightStudio",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card1",
    location: "Locatie",
    days: "Za & Zo aanwezig",
    address: "Adres",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&q=80", name: "Abstract Composition in Purple", bio: "SCHILDERIJEN" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1543165365-07232e8b2aa0?w=300&q=80",
    imgAlt: "Russell Ferrer Profile",
    title: "Russell Ferrer",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card2",
    location: "Locatie",
    days: "Zo aanwezig",
    address: "Adres",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1543165365-07232e8b2aa0?w=600&q=80", name: "Equestrian Monument", bio: "BEELDHOUWKUNST" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=300&q=80",
    imgAlt: "YANGHONG YU Profile",
    title: "YANGHONG YU",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card3",
    location: "Adres",
    days: "Za aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80", name: "Colorful Abstract Strokes", bio: "MODERNE KUNST" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=300&q=80",
    imgAlt: "Mayur Deshpande Profile",
    title: "Mayur Deshpande",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card4",
    location: "Adres",
    days: "Za & Zo aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80", name: "Blue and Yellow Abstract", bio: "ABSTRACT" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1506057213367-028a17ec55e6?w=300&q=80",
    imgAlt: "DOKYUNG KIM Profile",
    title: "DOKYUNG KIM",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card5",
    location: "Adres",
    days: "Zo aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1506057213367-028a17ec55e6?w=600&q=80", name: "Street Artist at Work", bio: "STRAATKUNST" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=300&q=80",
    imgAlt: "Jené Stephaniuk Profile",
    title: "Jené Stephaniuk",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card6",
    location: "Adres",
    days: "Za aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=600&q=80", name: "Red Blue Abstract", bio: "ABSTRACT" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=300&q=80",
    imgAlt: "Zalfa Imani Profile",
    title: "Zalfa Imani",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card7",
    location: "Adres",
    days: "Za & Zo aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=600&q=80", name: "Contemporary Sculpture", bio: "BEELDHOUWKUNST" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&q=80",
    imgAlt: "Teresa Profile",
    title: "Teresa",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card8",
    location: "Adres",
    days: "Zo aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80", name: "Digital Yoga Art", bio: "DIGITALE KUNST" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=300&q=80",
    imgAlt: "Unknown Artist Profile",
    title: "Unknown Artist",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card9",
    location: "Adres",
    days: "Za aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&q=80", name: "Black and White Strokes", bio: "ABSTRACT" },
    ],
  },
  {
    imgSrc: "https://images.unsplash.com/photo-1550684376-efcbd05ce3eb?w=300&q=80",
    imgAlt: "Artist 10 Profile",
    title: "Milo Y",
    description: "Biografie van de kunstenaar zelf (deze vult degene uit eindelijk zelf in)",
    link: "card10",
    location: "Adres",
    days: "Za & Zo aanwezig",
    address: "Straat",
    postcode: "Postcode",
    phone: "Telefoonnummer",
    email: "Email",
    artworks: [
      { imgSrc: "https://images.unsplash.com/photo-1550684376-efcbd05ce3eb?w=600&q=80", name: "Dark Modern Canvas", bio: "MODERNE KUNST" },
    ],
  }
];
